
alias ll='ls -l'
alias md='mkdir'
alias rd='rmdir'
alias gps='git push'
alias gcl='git clone'
alias nbrc='nvim ~/.bashrc'
alias gcmt='git commit -m'
alias gs='git status'
alias gcm='git commit -m '
alias gad='git add ./'
alias gsh='git push'
#createFile
alias cf='touch'
alias ~='cd ~'
alias grep='grep --color=auto'
alias ..='cd ..'
alias cls='clear'
alias mkdir='mkdir -p'
alias x='exit'
alias gd='gedit'

alias p3='python3'
alias ncv='npm create vite'
alias nrd='npm run dev'
alias nrb='npm run build'
alias nrt='npm run test'
alias nmn='nodemon'

alias pncna='pnpm create next-app'
alias pncv='pnpm create vite'
alias pnrd='pnpm run dev'
alias pnpi='pnpm install'
alias pnin='pnpm init'
alias pnra='pnpm run android'
alias pnrb='pnpm run build'

alias bcv='bun create vite'
alias bcna='pnpm create next-app'
alias brd='bun run dev'

alias saud='sudo apt update'
alias saug='sudo apt upgrade'

alias ny='netlify '
alias vcl='vercel '

