# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias md='mkdir'
alias rd='rmdir'
alias gps='git push'
alias gcl='git clone'
alias nbrc='nvim ~/.bashrc'
alias gcmt='git commit -m'
alias gs='git status'
alias gcm='git commit -m '
alias gco='git checkout '

alias gad='git add ./'
alias gsh='git push'
alias cf='touch'
alias ~='cd ~'
alias grep='grep --color=auto'
alias ..='cd ..'
alias cls='clear'
alias mkdir='mkdir -p'
alias x='exit'
alias p='cd ~'
alias x='exit'
alias svba='source venv/bin/active'
alias ddc='cd ~/Documents/'

alias dd='cd ~/Downloads'

alias i='cd ..'
alias cc='code .'
alias gd='gedit'

alias p3='python3'
alias ncv='npm create vite'
alias nrd='npm run dev'
alias nrst='npm run start'

alias nrb='npm run build'
alias nrt='npm run test'
alias nmn='nodemon'
alias nscnin='npx shadcn-ui@latest init'
alias pnscc='pnpm dlx shadcn-ui@latest add'

alias pncna='pnpm create next-app'
alias pncv='pnpm create vite'
alias pnpi='pnpm install'
alias pnin='pnpm init'
alias pnra='pnpm run android'
alias pnrd='pnpm run dev'
alias pnrdv='pnpm run develop'
alias pnrb='pnpm run build'
alias pnscnin='pnpm dlx shadcn-ui@latest init'
alias pnscc='pnpm dlx shadcn-ui@latest add'
alias ntl='nautilus .'

alias bcv='bun create vite'
alias brd='bun run dev'

alias saud='sudo apt update'
alias saug='sudo apt upgrade'

alias ny='netlify '
alias vcl='vercel '
